# Hostname of the manager and the compute nodes.
hostname_manager: manager.openstack.site
#hostname_compute: compute.openstack.site

# The passwort that should be used for the system user 'stack'.
stack_password: secretsecret

# The password that should be used for services like the database or queuing.
service_password: secretsecret

# The password that should be used for the OpenStack admin user.
admin_password: secretsecret

# The public SSH key that should be used for the system user 'stack'.
stack_sshkey: AAAAB3NzaC1yc2EAAAADAQABAAABAQDQdgM/Ph/dwJIomjqx9j2JxDR5St26OCql8cWpGy6Spd7v6g7hlpBTMl01Jr3bCvdwEb+SDBc/SSQ5W01I1YSOAqivA1YyRWCtRbLnQQQEbxCzN7rQXHo2I4NTLQM/dbDtWGgEuw70SH+YsnHnGRWEEPyu5LJF/7ZEbNbfx145BzocmUKoaul951fWSqS1qPZjuwIJGvasM5sQR8XE7uA1mD3lF7Qi/MhYVGmxYDwgISlaHQXqE3kpxv/H2lpZvhJiwxBc9elEyj+5YqDMJGqo8u/rHC0IGxv1fwPLWxe/avxLbZ282yuEQofj6oEG1uikQ9513xqBgyw1iY3ISk+Z

# Define the setup mode to install the environment.
# valid values: grenade, devstack
# default value: devstack
setup_mode: devstack

# What interface on the host should be used for a bridge will often be eth0,
# but vagrant needs to know for sure. This needs to be the full string
# descriptor of the interface. On some systems this can be something annoying
# like 'en1: Wi-Fi (Airport)'. Vagrant will not use this setting unless you get
# it exactly right.
bridge_int: eth1

# A non upstream for the base box, used to speed things up. Choose one of
# box_name (for a locally added box) or box_url for the url of a nearby box.
#box_name: 'my.favorite'
#box_url: http://gallifrey/vagrant/devstack-2014-02-19.box

# Non upstream Git URL to fetch Devstack from instead.
#devstack_git: /home/vagrant/openstack/devstack

# If you have code on a different branch than master, you can set it here.
devstack_branch: stable/juno

# You can specify a proxy, for example https://github.com/tmatilai/polipo-box,
# to be used for HTTP connections to speed things up.
#proxy: http://10.0.10.30:8123/

# Uncomment below to setup LDAP on the management node and use it as backend
# for keystone.
#use_ldap: true

# You can specify stable MAC addresses to keep this from resetting on every
# create.
#mac_address_manager: 0800274a508c
#mac_address_compute: 0800274a508d

# It is possible to use a hostonly-network instead of a bridged network when
# setting the parameter use_bridge to false.
use_bridge: false

# When using a hostonly-network it is possible to specify static IP addresses
# using the following parameters. If those parameters are not specified DHCP
# will be used.
ip_address_manager: 10.0.10.10
#ip_address_compute: 10.0.10.20
